[modsecurity]
enabled = true
port = http,https
filter = modsecurity
logpath = /var/log/nginx/error.log
maxretry = 5
findtime = 600
bantime = 3600
banaction = nftables

[modsecurity-aggressive]
enabled = true
port = http,https
filter = modsecurity-aggressive
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 600
bantime = 86400
banaction = nftables

[nginx-limit]
enabled = true
port = http,https
filter = nginx-limit
logpath = /var/log/nginx/error.log
maxretry = 3
findtime = 60
bantime = 3600
banaction = nftables

[scanner-probe]
enabled = true
port = http,https
filter = scanner-probe
logpath = /var/log/nginx/error.log
maxretry = 3
findtime = 3600
bantime = 604800
banaction = nftables
