[Definition]

ignoreregex =

datepattern = {^LN-BEG}%%Y/%%m/%%d %%H:%%M:%%S

failregex = ^.*\[client <HOST>\].*ModSecurity: Access denied.*\[msg "Penetration testing tool.*"\].*$
            ^.*\[client <HOST>\].*ModSecurity: Access denied.*\[msg "Scanner.*"\].*$
            ^.*\[client <HOST>\].*ModSecurity: Access denied.*\[msg "Automated attack.*"\].*$
            ^.*\[client <HOST>\].*ModSecurity: Access denied.*id "100121".*$
