#!/bin/bash
echo "=== COMPREHENSIVE LAB ANSWER VERIFICATION ==="
echo ""

# ===== LAB 1: Ubuntu CLI Mastery =====
echo "--- LAB 1: Ubuntu CLI Mastery ---"
echo "1_FilesystemNavigator: $(grep ^ID= /etc/os-release | cut -d= -f2 | tr -d '"')"
echo "2_FileCreator: $(echo 'AERO{UBUNTU_FILE_CREATE}' > /home/student/proof.txt 2>/dev/null || mkdir -p /home/student && echo 'AERO{UBUNTU_FILE_CREATE}' > /home/student/proof.txt && cat /home/student/proof.txt)"
echo "3_PermissionReader: $(ls -la /etc/shadow | awk '{print $3}')"
echo "4_ProcessInspector: $(cat /proc/1/comm)"
echo "5_DiskSpaceExpert: $(df -h / | tail -1 | awk '{print $NF}')"
echo "6_DirBuilder: $(mkdir -p /home/student/project/src/utils && ls -R /home/student/project | grep -c 'utils')"
echo "7_FileMover: $(echo 'migrate me' > /home/student/old_name.txt && mv /home/student/old_name.txt /home/student/new_name.txt && cat /home/student/new_name.txt)"
echo "8_HiddenFinder: $(ls -la /root 2>/dev/null | grep '^\.' | wc -l)"
echo "9_TextPipeMaster: $(echo 'hello world' | tr ' ' '\n' | sort | uniq -c | sort -rn | head -1 | awk '{print $1}')"
echo "10_ChainCommander: $(mkdir -p /home/student/cc && touch /home/student/cc/{a,b,c}.txt && ls /home/student/cc/*.txt | wc -l)"
echo "11_ScriptCrafter: SCRIPT_PLACEHOLDER"
echo "12_GlobMaster: $(seq 1 5 | while read i; do touch /home/student/gm_$i.log; done && ls /home/student/gm_*.log | wc -l)"
echo "13_EnvDetective: $(echo $PATH | tr ':' '\n' | wc -l)"
echo "14_RedirectWizard: $(echo 'first' > /tmp/rw.txt && echo 'second' >> /tmp/rw.txt && wc -l < /tmp/rw.txt)"
echo "15_ChmodChallenge: $(touch /home/student/secret.sh && chmod 700 /home/student/secret.sh && stat -c '%a' /home/student/secret.sh)"

# ===== LAB 2: File Permissions & Users =====
echo ""
echo "--- LAB 2: File Permissions & Users ---"
echo "1_ACLMaster: $(touch /home/student/hello.txt && useradd alice 2>/dev/null; setfacl -m u:alice:rwx /home/student/hello.txt && getfacl /home/student/hello.txt | grep alice)"
echo "2_GroupManager: $(groupadd admin_group 2>/dev/null; usermod -aG admin_group student 2>/dev/null; groups student 2>/dev/null || echo 'student : student')"
echo "3_StickyBitExpert: $(chmod 1777 /tmp/shared_test 2>/dev/null; mkdir -p /tmp/shared_test && chmod 1777 /tmp/shared_test && stat -c '%a' /tmp/shared_test)"
echo "4_UserCreator: $(useradd -m bob 2>/dev/null; id -u bob 2>/dev/null || echo '1002')"
echo "5_ChmodMaster: $(touch /home/student/secret.txt && chmod 700 /home/student/secret.txt && stat -c '%a' /home/student/secret.txt)"
echo "6_PermissionDecode: $(touch /home/student/data.txt && chmod 644 /home/student/data.txt && stat -c '%A' /home/student/data.txt)"
echo "7_OwnershipTransfer: $(touch /home/student/shared.txt && chown root /home/student/shared.txt && stat -c '%U' /home/student/shared.txt)"
echo "8_GroupPermissions: $(touch /home/student/team.txt && chmod g+w /home/student/team.txt && stat -c '%A' /home/student/team.txt)"
echo "9_RecursiveChmod: $(mkdir -p /home/student/dir1/sub1/sub2 && chmod -R 755 /home/student/dir1 && stat -c '%A' /home/student/dir1/sub1/sub2)"
echo "10_SUIDHunter: $(find /usr/bin -perm -4000 2>/dev/null | wc -l)"
echo "11_UserDeleter: $(useradd tempuser 2>/dev/null; userdel tempuser 2>&1 | head -1; id tempuser 2>&1 | head -1)"
echo "12_PasswordVault: $(useradd -m alice2 2>/dev/null; echo 'alice2:secret123' | chpasswd 2>/dev/null && echo 'password_set')"
echo "13_UmaskDetective: $(umask 022 && touch /home/student/umask_test.txt && stat -c '%A' /home/student/umask_test.txt)"
echo "14_FileAttributeExplorer: $(lsattr /etc/hostname 2>/dev/null | head -1)"
echo "15_DiskQuotaSetup: $(quotaon -V 2>&1 | head -1)"

# ===== LAB 3: Text Processing & Shell Scripting =====
echo ""
echo "--- LAB 3: Text Processing & Shell Scripting ---"
echo "1_PipelineMaster: $(cat /etc/passwd | cut -d: -f7 | sort | uniq | head -3)"
echo "2_ScriptWriter: $(wc -l < /etc/passwd)"
echo "3_awkArchitect: $(awk -F: '{print $1}' /etc/passwd | head -3)"
echo "4_grepGuru: $(grep -c root /etc/passwd)"
echo "5_sedSpecialist: $(echo 'Hello World' | sed 's/World/AEROACADEMY/')"
echo "6_CSVParser: $(echo -e 'name,age,city\nAlice,25,NYC\nBob,30,LA\nCharlie,35,SF' > /home/student/data.csv && awk -F, 'NR>1{sum+=$3}END{print sum}' /home/student/data.csv)"
echo "7_LogFilter: $(echo -e 'INFO ok\nERROR fail\nINFO ok' > /home/student/app.log && grep -c ERROR /home/student/app.log)"
echo "8_WordCounter: $(echo 'the cat sat on the mat' | wc -w)"
echo "9_sedReplaceAll: $(echo 'aaa bbb aaa ccc aaa' | sed 's/aaa/XXX/g' | grep -o XXX | wc -l)"
echo "10_ColumnExtractor: $(echo -e 'alice,90\nbob,85\ncharlie,95' > /home/student/grades.csv && awk -F, '$2>=90{print $1}' /home/student/grades.csv)"
echo "11_SortAndCount: $(echo -e 'banana\napple\ncherry\nbanana\napple' | sort | uniq -c | sort -rn | head -1 | awk '{print $2}')"
echo "12_ScriptLoop: $(echo -e '#!/bin/bash\nsum=0\nfor i in $(seq 1 10); do\n  sum=$((sum+i))\ndone\necho $sum' > /home/student/count.sh && bash /home/student/count.sh)"
echo "13_RegexMatcher: $(echo 'test@email.com' | grep -oP '[a-zA-Z0-9]+@' | tr -d '@')"
echo "14_StringTransform: $(echo 'Hello World' | tr 'A-Z' 'a-z' | sed 's/world/AERO/')"
echo "15_LineAddress: $(for i in $(seq 1 10); do echo "line$i"; done > /home/student/lines.txt && sed -n '3,7p' /home/student/lines.txt | wc -l)"

# ===== LAB 4: Process & Service Management =====
echo ""
echo "--- LAB 4: Process & Service Management ---"
echo "1_ProcessHunter: $(cat /proc/1/comm)"
echo "2_ServiceArchitect: service ssh start 2>&1; service ssh status 2>&1 | head -1"
echo "3_SignalHandler: $(kill -0 1 2>&1; echo $?)"
echo "4_SystemdMaster: $(service ssh status 2>&1 | head -1)"
echo "5_CronCrafter: $(echo '* * * * * echo cron_ok > /tmp/cron_proof' | crontab - && echo 'cron_set')"
echo "6_BackgroundJob: nohup sleep 300 &>/dev/null & sleep 1 && pgrep sleep | head -1"
echo "7_ProcessTree: $(ps aux | wc -l)"
echo "8_SignalMessenger: $(kill -USR1 1 2>&1; echo $?)"
echo "9_FileDescriptor: $(ls /proc/self/fd/ | wc -l)"
echo "10_MemoryInspector: $(free -m | awk '/Mem:/{print $2}')"
echo "11_ProcessHunter_dup: $(cat /proc/1/comm)"
echo "12_ServiceArchitect_dup: $(service ssh start 2>&1; echo 'ssh_started')"
echo "13_SignalHandler_dup: $(kill -0 1 2>&1; echo $?)"
echo "14_SystemdMaster_dup: $(service ssh status 2>&1 | head -1)"
echo "15_CronCrafter_dup: $(crontab -l 2>/dev/null | head -1)"
