-- =============================================
-- GENERATED FLAG UPDATES
-- Normalized: trim + lowercase + collapse whitespace
-- =============================================

-- Update flag descriptions (redesigned for Docker compatibility)
UPDATE "LabFlag" SET description = 'Run: cat /proc/1/comm. What is the name of PID 1 (init process)?' WHERE title = 'Process Hunter';
UPDATE "LabFlag" SET description = 'Start the SSH service, then run: service ssh status 2>&1. Submit the full output status line.' WHERE title = 'Service Architect';
UPDATE "LabFlag" SET description = 'Run: kill -0 1 2>&1; echo $?. What is the exit code of checking PID 1?' WHERE title = 'Signal Handler';
UPDATE "LabFlag" SET description = 'Run: service ssh status 2>&1. Does sshd show as running? Submit "is running" or "is not running".' WHERE title = 'Systemd Master';
UPDATE "LabFlag" SET description = 'Run: grep -c root /etc/passwd. Submit the count of root entries.' WHERE title = 'grep Guru';

-- Update flag answers (verified or redesigned)
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$U20D3/Bqei9oLrL4AMHeseXZ6YY8H3qdm5TVbCASwghSjLpPzTMbO' WHERE title = 'ACL Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$KY/k3ahXLHGvfQB8eqsMC.tj.iSXGs09yr5cHduVxBtq7Z3gHYlgS' WHERE title = 'Group Manager';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$61sTTZFinsHVx0/gZnjVAOQI5pPl8jFyKZodHMspVTlzvTk2aYoQe' WHERE title = 'Sticky Bit Expert';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$ilP9JfkURmIkSpFu0KU2UOHB7NBtbJUJQzm6Gj.mMbAZrQ/NLUtGC' WHERE title = 'User Creator';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$WrTTMDDhw/vKYkABOWXxUeT2DgN322Sm5bXCdkzZOtbQ6waxjDdR6' WHERE title = 'chmod Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$HCb8iNw5AtYqglbMADoO8OmCUgNfAIEM9IN/acRJysQ0uw2ZHLQ6W' WHERE title = 'Pipeline Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$W4JQdqmnAwhsJWiVYHtF1eDld0upK2htverexSODPVXjXok24TKP.' WHERE title = 'Script Writer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$kS.vzjqOsJIE.ArDiXeBB.PvW2pmT7wZumSgIiysjuIaWbd1M7uga' WHERE title = 'awk Architect';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$nftYz/QQjVWI/QxLuF4AReaCHZsHLaV9DhEZoKir.bC6HY9AyfX6K' WHERE title = 'grep Guru';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$1I2ujyyFgo7DCONtu336p.zLANLH2ZoB/44Su/ajM5S/G/OTwo1cy' WHERE title = 'sed Specialist';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$wPvQu9YWUZ9TluVb4Cd2YuWhPF50Mm8B0JqBf3entBjrJJEXB.a4q' WHERE title = 'Cron Crafter';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$utgoBcJMpc21KNXYrt2/yejZ5q8vCHarVI1iGh0EIe6wQlQMWwNLS' WHERE title = 'Process Hunter';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Nh44IoKN57RgAmE61VU7Ke9.uVC80uTao7lXmkdV3h4tKzzQTzzk2' WHERE title = 'Service Architect';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$fIUiNykq/l8qrVkJWxLay.IZf0kvtKZ0G.I/ZvHQKNpi.zIuwJTj6' WHERE title = 'Signal Handler';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$h/XPi2hIcL2QxXVdZJnSruCS2D8oICqLhM4LkDxob/DwuX3XaNk0W' WHERE title = 'Systemd Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$CWJB4EWENu2ZWOcJHfkNtuU8XhFi/WpCJ7lzorX8FQdqpAyWniIP6' WHERE title = 'Root Auditor';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$nUEpn.Py6pgwVSbj/kwhI.Dw3LWzdmWFCgpzXGL7d7/W4ZjYkXKvC' WHERE title = 'SSH Hardened';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Ez7Z3JSlDCTxyVSKH9Noz.APyc6eoJGSWPilKqImWOgmuzQIjttfO' WHERE title = 'Firewall Active';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$0JH48PsDrO/MjBcCQ91GdO5WmjuByzY2CdgW/2kNpdG21yehAnk7K' WHERE title = 'fail2ban Guard';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$tiu/Kp.5QpLBDBCDNnLlv.qFIEXOB46vXcclex5U3iL1e2JCCw1Eq' WHERE title = 'AIDE Watcher';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Og58Ecr98txJgAlfS3UvLu/ZikHPcZbW8zESpVBVOrlOBCrpCMODq' WHERE title = 'SELinux Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$1LKorBql2Cf1CDUtLzSXSuQ7ZVcdxDfdqvBjLDKg2EYb0dHjJSXQa' WHERE title = 'Package Expert';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$GZUfn0A6.gHnBhp/9CUkVeVCHIzdVnN5nc2Z6tZNV0jpiIN/jJh8S' WHERE title = 'Firewall Commander';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$kL7QICCo1rVTuTLMaRmipuISJp.lqc4z2Z1tFApYG764vkhEUtmp.' WHERE title = 'SELinux Auditor';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$saHme1v1i4IpGy7KPHY.FuJiUv2Ov3qkM.yW/G4pVVheV1H2ve2FO' WHERE title = 'Systemd Architect';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$a4.w1dBv9g2iKqp32A79tu1u66t1z4AWEYtJM7yRC58CdCBEZUbD.' WHERE title = 'Log Analysis Output';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$CF/vS8MOuChI.YES8hV9d.wJfd4x60XQM9EUHtstJD2PtoRsa.tai' WHERE title = 'rsyslog.conf Rules';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$2HqOyPFAttC0LO0fpZ2ZNeG40C6/y.SyP6zsovYdH5n4ef6Vv/ePe' WHERE title = 'TLS Port';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$EKpfLfA08gz.7CxHF1riWOhDynst24V1Mli5AwMd7ttoBwxFmye4W' WHERE title = 'Logrotate Config Syntax';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$pI6WlWbeOqshyrHadXrACe7TL8RCg5J/Aj5tW6GohM9BFM.dlqnhi' WHERE title = 'Rotation Count';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$EUiVumHFdosZ67ZyP6wYfuZF7yPP1cRJssjPoMfvdye6Ahp3ruBj2' WHERE title = 'BOLA Specialist';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$uoBO8lTJlH6HOq3u9Jdu/utCOiXXFNET8qiKezr/yqFGqvVZ.F4Uy' WHERE title = 'JWT Architect';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$mkiJXQQFekTqO1CxeKLjuO9Mu06w2YJJZctJ4rbvaeTDZBUKMlfx.' WHERE title = 'Database Version';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$peC76P1zivJAHr0iZS17He2K/VjvG69XLAW24Re1yqBUzaomWGQv2' WHERE title = 'RCE Execution';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$.pI8rXSjYUU7zqzV3WEKLOp78mzbMPAab4MfFlK/2YP/TvEG1UmKa' WHERE title = 'Credential Brute Force';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$4ysIJ.7DFrJQbl2r2.cSJ.fvMelptHafdS/dHC4kYeZlVgX9fxG6a' WHERE title = 'Web Shell Deployment';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$IooZNrLK8kXZjp9y.v0ehuPzXxeJAYZ73q9BtTaKas/xfVVL3yZtW' WHERE title = 'Admin Session Token';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$CYZVcS1IU1blpqoyM.XUlOHrGKyRaCsRpPN/cBW5Uc7XkBVp/HULW' WHERE title = 'System Password File';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$cd1Z0eN.MjoLPR57BAY5B.EzMvHUDwVfx14BwVW4FG2T9lZNX4Xnq' WHERE title = 'Admin Access';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Q2o3gdvUSpV8W/4s4TNHfetb5J1Vp4TZ7CyawmSUPakdqC6i81Bj2' WHERE title = 'Hidden Feedback';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$qxI.tzpXSY5yBnifjH1Vn.YMZactu92udN.Mhr8LW6h1K8frDMQsy' WHERE title = 'Deserialization King';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$pE1oQibRoYAfLbEjexyyw..EoqaokhmjpKseqIxzS4K2BS4h6.imq' WHERE title = 'Path Traversal Expert';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$pk3mHoWwEcG21FexT0gzmeAE8A1z2vpnnEtvxvBRU4IJgxLJxrTIS' WHERE title = 'Mass Assignment Hunter';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$hCteoBfCwvmGFYlXleosluvWKOCkZOQnynqAqWpaST0w0.4OPZUlK' WHERE title = 'NoSQL Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$L/3DJ9XkZxfWi/4XFzm6J.0wNQs5lN9a32uI7v/AlGEbwWOYvnVhm' WHERE title = 'Database Engine';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Ty14x6ir8ySp6fNi3Go7GelbFO6gxXcn8b5leKRJBD06xc/4C5dkC' WHERE title = 'SQL Commands Output';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$iMs3SiMSdw5IfGsvF47TeeH6y8ZrutcyLReBpm.OuQgu6aFHwttru' WHERE title = 'User Privileges';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$2jMCmTlLY249XuJx6fbtNe.uWwfL5RorLsT23q1ZJQOX.HeU7kq0C' WHERE title = 'Replication Status';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$.47U4rkdpELGLx1pD13Tje5/NMd1mC2FEOXx4gdiv4hCvSVa7rwi.' WHERE title = 'Backup Verification';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$NV4eQzCMjj6C9OfCpclDP.A1H22inMp3OHzGxsljg8O74azzbctom' WHERE title = 'Load Balancer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$oMYOnAutISQT9G8tSqY/W.imB7BS0vOP6aKGiIgVR2sbh/jdXDkLm' WHERE title = 'Rate Limiter';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$.G2Sr7RSJ2ep2ybZ.OTyIePq9oFBlq6e8JafP99T9xq6BIALvmeXK' WHERE title = 'Reverse Proxy Pro';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$nULVtVPM3NS.dfhfFBLZgO1TStWNzMpBIKzycgHBsq.BtmbnR0pni' WHERE title = 'SSL Engineer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$S9TdApE9Q79kRJFzWtE.WuuUoNcCCtE/ft1N5bJNbdKDe.OEfX6F6' WHERE title = 'Vhost Builder';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$TROoJo9ZINjIWrEcqvEdLupk.46K4dAtkCvhc4HliZq88dZl0bcna' WHERE title = 'Default Port';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Log9bTTJBbycD.OxelQIx.27TiSPgs3aB250EL0N3bH3pGu3H4B0K' WHERE title = 'Role Attributes';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$TxVvjMq9UM/CX9RJxeFJIusSupWJ9Nr8ZaK2YVHa7n1dHraKz3Ldi' WHERE title = 'pg_hba.conf Entries';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$o8WlFOw7X6xnY3QvzvQVj.kI6kBmfOTVzlOBJ0JcjQQh/arVooZ32' WHERE title = 'WAL Archive Status';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$2Qf90F9wF16fmZYHlv.7Je.SoTlMjPlQy/jx5eJkpqy2Hw5Ip.HHa' WHERE title = 'dig Query Results';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$nPSlCxI/AZ8OpU3ZSplaDuMcS3e9Fbhgl7lj56goExrTvENkT5Dny' WHERE title = 'named.conf Options';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$k1YOUlY2H7nGc.vqroix9OdwjE1kFoZfeSDyX21F0sW21Vuxn8IUC' WHERE title = 'SOA Record Values';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Q3RsUDT3z9woeweg985iFeM75pH2sazi2prrVjjp0EvQRPcvqSN8y' WHERE title = 'Zone File Syntax';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$WtOe0PFQxBq3hM0wZytCh.bPxVp6ls99Ba8k3XQbO1LWHgMX.S5d6' WHERE title = 'DNSSEC Key Generation';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$vVfKKxpYAEr5kSTILBSKkewXVRLZceizBOCG8e9Bni.AWYLpUGPWO' WHERE title = 'FS Expert';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$BCTgnAfNqD.Dki8qKdMAj.9zXAnVcg4CqY865hSzws137vc6nF922' WHERE title = 'PV Creator';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$zWhaqHjN728LsEo5IWTDReyIVjRG4pmiqYyMnV5GEs47LnBqBgSSe' WHERE title = 'VG Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$tPRCVQ2FNaPrX//Dsd4WGu5zbnCoZCqgQT707xIbGKf9vVGXY6I9S' WHERE title = 'LV Engineer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$DXeIp5fgZo.VS.ete0gmn.UwhH1C.66//NrcQKnL8tr8wHUCw9lmW' WHERE title = 'RAID Builder';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$eHNAHeNc1Z62Y0U/3ImOIujO6VwJKwSoxeGErr4pkkYy0uR4RkQPK' WHERE title = 'Backup Checksum';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$DuI/U2SSLvwiJwjsScCFH.GeCs0QjAwpfW/0T17Xxie9yKeo1fRgS' WHERE title = 'Cron Schedule';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$R1tCVjLMNbEOvqFWj7FauOBWA1vUh9swECdshP9mvufzuKA.Cfgti' WHERE title = 'Rotation Script Logic';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$NILF0zmyvbdh4EfCFyk09uzMH7qogTnaWOLCYrhenIL2lRATDqMyC' WHERE title = 'tar Archive Sizes';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$8MabVRIF7CWffgucRloyheRyb.N/dUgtxz/f8dNzU/wjjo//0pkrO' WHERE title = 'rsync Dry-Run Output';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$5r1dNJyjpLVls6vf4hS.Z./3fDeYpV4fYsFCDC8r73IZlETR3mpd2' WHERE title = 'Container Runner';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$M64X2wrJPwG.ABsKMJu9EO66as20ifwdDE3e4bHKFI8E40NDwNQ9.' WHERE title = 'Dockerfile Author';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$hW2VCiBNh0nhY8.gPa88X.PC0OuzwfQv4clpYgvW18fKDXDi4j6me' WHERE title = 'Compose Architect';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$nw9OhXpyDI.XcBbDkF7Bouh85QfH/JPZMDdvVsy.2YnopUy38t6NW' WHERE title = 'Network Engineer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$kicwLb6bXMpLiIMmtWLCrOIg0ATwEKI.O4cQ89VQhpD9RpyOW5flC' WHERE title = 'Volume Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$HSziyBbqzV7P4e5YLvCqj.PZbmoFLaDZ3bF.yCFZAv9.xlp1wh6sW' WHERE title = 'Dovecot Config';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$QIjbKNxG8TttNxZb8wd6SOE633xKVWRWzbSg99uBvXIGgSOV.lqHy' WHERE title = 'Postfix main.cf';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$DQqlOetv03p3ucb0IwAnYOl1NBiNdQ0BAviWC8yRWYj5k1CabDcQK' WHERE title = 'TLS Certificate';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$kYS5p6mrLNeFa./De0nSC.lz3SMSM5OYgzmtZHddTdB1q73KlaV5O' WHERE title = 'Mail Delivery Test';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Ou8Od8.guMbYXb8nxWzbquO7ORKsWwCUFnR8NbLF7VB53MyPsBQy2' WHERE title = 'Port Configuration';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$An4IrIWr6/ARaE4RRfgWjuQsTMnkbrcnk6QzXd17OUMxTaJLFW5L2' WHERE title = 'Branch Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$q.Tgza/w88pYpHaCa6kDgOCPMU7lnaCZogTWsTco2fHX8f9eaGq76' WHERE title = 'Gitea Deployer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$hxP9cQVKruiuDHM.mSs0NOwfp5YQwZ33PjmxXRHOH2XAULBblX2UO' WHERE title = 'Repo Creator';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$RCbJjReHwwyz6fus0MNQUui9JV51v5juZR3iSj3uCeF6s4wP0B4CO' WHERE title = 'Hook Engineer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Xv/m3Xk4pBm/ymvM0pJPve1M.A49fB2ifk/ypM7yMPwseL3KVKEUa' WHERE title = 'Conflict Resolver';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$b1BFf24QNb3ZmURVZiqQGua/WBB2O3ueDrJ2sgky9in2EuGzl1aE2' WHERE title = 'Inventory Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$KxKgDZOfyR6YOrh/PGCvGOU7IzwU/DWs9cHD7QxFDIYiQnBLdxvHa' WHERE title = 'Playbook Writer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$U3118Kjt2kGa2njwVVg2lOV.mx3.00FtuedRVR3TmgIl5yLnzEee6' WHERE title = 'Role Builder';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$YxeVdIfTGS3wiCD0boWapuB.UQQXaYfru0a9z.9o1oSNsBSNwE/Qu' WHERE title = 'Vault Keeper';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$OPdmi/IQdYtzRVtYiMbXc.EUQ8uxXm8BrYWo/Q6.0zUTG7ANa4obi' WHERE title = 'Backup Script';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$OKiQeTT1Ydi3yRRYXkUGpeiDdUf/a1frRab.ncSnbZNZ9qDaNqzmi' WHERE title = 'PromQL Query';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$RaRpu3iL7/9QgT/lhrfeIu6Zc3ZQUz5OBif3HTGKQsNEScCKDiVrW' WHERE title = 'prometheus.yml Config';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$l3g8gm3l8ZA1UU4DrzbRAeEfggK/3uac2j6o.wFzm5mpbfk1U15wC' WHERE title = 'Scrape Targets';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$f/kE.oYcCKuIr3p.YPOeCOZgNTmtYOgjbcaXywKQgHYbDZpFNSS9C' WHERE title = 'Alert Rules';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$T5gZjcipI.yAn9RoqAk0JeXgfRyJ4nhofR4YBo2liajGVPc.U.Lu6' WHERE title = 'Grafana Dashboard JSON';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$JrLO5DjFULiSzVGRr24S3O4r/oOSS96O5F2OlVw.AYgxK3/B3g4kW' WHERE title = 'Port Scanner';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$ocdktnYpy2.C8k0HiKcO7eFXyzVrrS0uQ24VqCpdnr.Cp9pQMBZc2' WHERE title = 'Service Detector';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$BTgcsfDRgSXmomTkaRRCDu6L0gUHUhawsqYH.UWXfdqk0N5gWPo1q' WHERE title = 'DNS Enumerator';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$ThRvlRk2CmWhtV7698p8zuteahaolD7gd5cCX37RKp49MGOfbv6sa' WHERE title = 'Script Kiddie';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$.nUkffiHLbUlxW8TC2DhiePGR2mXT3Ge0wobolJRXUf6h9VoViLfq' WHERE title = 'OSINT Collector';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$bZmsy4pQKzbY6CcfVBhvEe0omYvQWfUNFk3ENeNgOl/yI97oDGk42' WHERE title = 'Kernel Identifier';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$IR5ahBwpbEpZ6df3BrVlG./OEf2oGLs28hc1z3STWhfi.HL6inWhq' WHERE title = 'Memory Analyst';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$NGelE1g/MFdMuQ/p13O2oODDWZP81eTQ0YrrZINgAcucPGtzQ6wZS' WHERE title = 'Module Inspector';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Q6VW0K.eBshAPM95VMamVelTfHERcApRfaElzYU/9BT9WWAqF4ACu' WHERE title = 'Proc Reader';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$z2W25EGserts0P8ySFFj9uuxJk4ehQ7Rc1fevzP.oREnAMCNTo2ae' WHERE title = 'Sysctl Tuner';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$ZHJej/cgPVPJyv6L3qxNVO5NCNNtG5epEfSdW4.CcdJhL8WPThacy' WHERE title = 'Profile Name';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$9wEeNCCytghyQNCAJgVAVeFxmDLyTZnQMl4IVhP0L0dpoPnQjeLtO' WHERE title = 'CVE Counts';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$nanHIeVg7Qef9piRwuDLnuVzoH3azYQf3Thc7zL8tMkXKKQM5lCzu' WHERE title = 'Compliance Score';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$qSCdfyni1mWWe1bFhJCsOedtFYEBKQg9ZNgYYtZIyhMXKoD3oaal6' WHERE title = 'OpenSCAP Scan Results';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$yuR5BOuHmS.t.rPHBU.3p.LzAZ/8SxVgkmg7IAJdDUEQMyB/vwwWa' WHERE title = 'Remediation Status';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$dEp7JddLL0b3gNmlLbms1ODbGOjfWZ5.HWk1VZIvgrJRT5wGjIzg.' WHERE title = 'CRS Activation';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$r1SsGFha2w1xjgmroS0E7uT52fUcLJIiw/N9EL.mzAJucKjwd7V0S' WHERE title = 'modsecurity.conf Settings';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$dF71chvFT9xWiufR/hN7R.cKiWvFGU4iR1zCjUFZc0FV7NGn3E9.6' WHERE title = 'Custom Rule Syntax';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$.Wrrtv6Jix3duyNWjUuEYOlkV3GxwfphTdYNrYNo8xXzafXaNfqAy' WHERE title = 'SQL Injection Test';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$jIgjK81i2zT62L17ttP2SOgZgOMjKrhBkx4HzsUMfFgkJgjPsvNKa' WHERE title = 'XSS Rule ID';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$6uDTsyfFGwj4QHClVnpDPubtKH0omOIUtNgp8pkfi77QGrwOd74XS' WHERE title = 'DB Connected';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$8lPqyyMmU2gLBgk5HeRVEe.OVoJ5OE7.XWM.4AoS3j/Mms9Ep.BLm' WHERE title = 'Exploit Finder';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$f5VGfx0n2zLF4QXaDJ9LSuhmV6aDoJNgA4OvgQoagVQ6ouNOWVixu' WHERE title = 'Module Master';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$1r6XwLRvDsAMH1BjhVwBneASkaSys3Pb7PTxzgHVZzCKl57l5TCLm' WHERE title = 'Payload Crafter';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$2OsHP.ldWB9sWD7y8NbfDuUnIMKTt3YAdAy/vK81okcuQz/O7hAP2' WHERE title = 'Script Writer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$iOowkXd83oIbae1J1GQGK.B.OtE8sRSPWjOrqczQ8UpuLZRkrJ3HS' WHERE title = 'kubectl get nodes';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$35NnxPlVvlcZCbgV.rAan.Z3ehJXEEjlBSbcTANHIqGC.xNxnvc8a' WHERE title = 'Calico Status';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$8WQM.jXQhuSsIiChycgddeX1gaRT8BbQb454kak5FRvQFr./ZTuEa' WHERE title = 'Pod Status';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$.M5ZSyYQkX.bee4mkyvDH.ts5eBe8SmmzCHQ1/idn2O8e4eioKAiS' WHERE title = 'Service ClusterIP';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$p6HTTh0CnlYETohXmdj5m.6Sj0LII0dwe9B5fqMKuJNjhj8Qo38cK' WHERE title = 'Container Runtime';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$YqcvX7LqERA6tMe9XIP9U.bqOfYKhY3kvBE3xW6Bc1v2bmpcOWDZC' WHERE title = 'Firewall Builder';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Wijobgxdh1nsuX3jiD.o0OneH8VEehNtgARlfBHmB/775FwHaSMki' WHERE title = 'VPN Engineer';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$VUsyMtWmoECMMdmqQPbfCemyDohHa8MyIRdQyLQm9QYkJyii32lnm' WHERE title = 'IDS Architect';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Ldwm.FyRf8gq6xFsN7Sq7.8GpFjS/QwopVEXraaAalGI0DpLsgu1C' WHERE title = 'Packet Analyst';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$s5mD4y/y6xDLHWLc4By9uOJ9KC0WoOGmbJuhCEn2D9LufsAFd9aHW' WHERE title = 'nftables Pro';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$R1Euz57hqGurZ47w7nNo1u43iFRd63VIhtZUTIU0h6wdSfl.qWJgG' WHERE title = 'strace Output Patterns';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$os4WokA/of/Auix7rUfWXuQw3pzSi/P.9bVU.kJAzn98mNyEOguCa' WHERE title = 'perf stat Results';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$YXaFeTwc97WtpuCKFvEiZuYls4scLtWbRvJ.7Wr5YoR3VXiZ1JFhy' WHERE title = 'ltrace Output';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$F0jjDdJBjKaXJq.bq45QJecrOmSw20Gt1EEFPlDBRlX1XnS7oJTUq' WHERE title = '/proc/[pid]/status Fields';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$zAYLeyhjs.sU9f2QA1BoheOjHRSQTrYzAeoQcR/.p5p4UVTD7BYDy' WHERE title = 'Flame Graph Title';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Y1NxeKse3dMzNt5PErvSvO2IweNkNIa3DnPrYw.Nzjip3Qg5ZfEyq' WHERE title = 'Lynis Scanner';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Ma0/PxmgKLxbm2q4r0nmXOXOqnzFdYga/ormY5OuHsRIJnfa7CCkq' WHERE title = 'AIDE Initialized';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$W/JKWwX0OEcJnU5NS.og5uIqJqajiXoMjxRyJMx9SN9q/yx4WHqj6' WHERE title = 'CIS Compliant';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$M..utVL51/OLRwGrkVG5YeQafKDeA4f2gcx0lAhfpJE9oU0dHpWOu' WHERE title = 'Audit Watcher';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$S3dZd5oRU3G3joI/9fs97eLDAwGeVbZZYuBq74E/81OaHMA2b61Oa' WHERE title = 'Report Generator';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$KS4447qOH4k2MxK/mapCgu3rFHr2haMmxxM/QxlhWN81T4ty8yA/i' WHERE title = 'Target Found';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$wKltiyCXdkeQt/PFqjFdTuArcavqSCEPJl72/EeGXGGbpCxoJDfNS' WHERE title = 'Service Enumerator';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$d/nIxQ0IFgiHpCXmIbxSEOQ4SJO11KKH/1aWlAMDw0VL4mrWjaJEG' WHERE title = 'vsftpd Exploit';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$d1uHK9JxRvzx8yd3F9/eaO5JdQ/2Pu3LK69Gfb6CHs2sP2LQR9.C6' WHERE title = 'Meterpreter Session';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$oSrdL1cW4BitTLmTswjUAOmXWvXH0XsXFZT8HLQVLVAkDPxeHPWLW' WHERE title = 'Hash Dumper';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$FJOBle./cYNa544INfnOH.ur5tpgC6jUVMO4kDR.o2EQ272GQzbva' WHERE title = 'haproxy.cfg Frontend';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$CcRMfi1G9DEHdad4Fm636eI7EEbRn1ZKEnRzuvLDqNQNhK.0NRCp2' WHERE title = 'haproxy.cfg Backend';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$Ctr5PbZLNODT3gnw4/sd5.s60GSP5D3S9dfhwzzjFVBcoNS6kLkja' WHERE title = 'VIP Address';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$0XWzzP8LLzUntQT9u3nbV.2WMFrdvkFbCZqZxMo6oYewT8P6rak3a' WHERE title = 'keepalived.conf VRRP Script';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$WxPD9i8iClZ422e3cpYRM.0ZuFgWL9y3APw3wMjXVCQ5hlhuzrw9.' WHERE title = 'Health Check Type';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$6aPRphT2CYpkABjQQcMeXuZSdlAzbISEMCezDmerdF.ah4tDakEC2' WHERE title = 'Firmware Analyst';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$ddb1n/ND17E5.3pN4b5WM.nKOY26MGrQsLtm.VWRz1/DBCHZ3hbOe' WHERE title = 'Metadata Hunter';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$D8IM8urVEDy.qL6xBUsc5.HHnhTZ2avZJNZXZve/FOk074pRMo6wS' WHERE title = 'Packet Inspector';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$kWmbP9oxXW3smbZNLoB.ie88wvI/SLv3pR/A6/iu4zDa5F6.eTSAu' WHERE title = 'Chain of Custody';
UPDATE "LabFlag" SET "correctAnswer" = '$2b$10$B7Z87O2aikVcKozlzVjurOxZ29y8ThgYaDV74yAtlqiQw1Rx.wsqS' WHERE title = 'File Recoverer';
